server.port=8080
server.address=127.0.0.1

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=public
spring.datasource.username=postgres.otkisarljnsnmnllftzu
spring.datasource.password=Baatraa12!@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public

app.jwt.secret=ejusys-super-secret-jwt-key-2024-random-string
app.jwt.expiration-ms=604800000

app.bootstrap-admin.email=admin@ejusys.com
app.bootstrap-admin.password=Admin1234!
app.bootstrap-admin.first-name=Admin
app.bootstrap-admin.last-name=User

logging.level.org.springframework.security=INFO